tunnel: 7488faec-a04f-463c-a3fa-cb6cd0b0a205
credentials-file: /etc/cloudflared/7488faec-a04f-463c-a3fa-cb6cd0b0a205.json

ingress:
  - hostname: api-vectraclip.vectracargo.com.br
    service: http://backend:3000
    originRequest:
      noTLSVerify: false
  - service: http_status:404
